//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechNews.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int postID { get; set; }
        public string postTitle { get; set; }
        public string postContent { get; set; }
        public int postStatus { get; set; }
        public int cateID { get; set; }
        public int hID { get; set; }
    }
}
