//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int aID { get; set; }
        public string aUsername { get; set; }
        public string aPassword { get; set; }
        public string aFullname { get; set; }
        public Nullable<System.DateTime> aBirthday { get; set; }
        public Nullable<int> aGender { get; set; }
        public Nullable<int> aPhone { get; set; }
        public string aEmail { get; set; }
        public string aAddress { get; set; }
        public Nullable<int> aStatus { get; set; }
        public Nullable<System.DateTime> aDateAdded { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> countryID { get; set; }
    }
}
