//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int hID { get; set; }
        public Nullable<System.DateTime> dateSubmited { get; set; }
        public Nullable<System.DateTime> dateAccepted { get; set; }
        public Nullable<int> typeAccept { get; set; }
        public Nullable<int> censorID { get; set; }
        public Nullable<int> posterID { get; set; }
    }
}
