//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int pictureID { get; set; }
        public string urlPicture { get; set; }
        public Nullable<int> postID { get; set; }
    }
}
